version: '3.7'

x-env-defaults: &env
  YARN_CACHE_FOLDER: /.yarn-cache

x-node-defaults: &node
  tty: true
  init: true
  image: node:18.13
  working_dir: /graphql
  volumes:
    - ~/.gitconfig:/etc/gitconfig
    - ~/.ssh/id_rsa:/root/.ssh/id_rsa
    - ~/.npmrc:/root/.npmrc
    - .:/graphql:cached
    - ./node_modules:/graphql/node_modules:delegated
    - yarn-cache:/.yarn-cache
  environment:
    <<: *env

services:
  bash:
    <<: *node
    working_dir: /graphql
    entrypoint: ["/bin/bash"]


volumes:
  yarn-cache: {}
